apiVersion: v1
kind: Service
metadata:
  name: spring_boot_service
  labels:
    app: spring_boot_app
spec:
  type: ClusterIP
  selector:
    app: spring_boot_app
  ports:
    - name: http
      protocol: TCP
      port: 80         # Exposed port inside the cluster
      targetPort: 8080 # Port your Spring Boot app runs on
